DROP DATABASE IF EXISTS `BANKACCOUNTS`; 
CREATE DATABASE `BANKACCOUNTS`;
USE BANKACCOUNTS;

DROP TABLE IF EXISTS `accountholders`;
CREATE TABLE `ACCOUNTHOLDERS`
(`FIRSTNAME` varchar(255),
`LASTNAME` varchar(255),
`NATIONALID` varchar(255),
`PHONENUMBER` varchar(255),
`BIRTHDATE` date,
`ACCOUNTTYPE` ENUM('CHECKING','SAVING'),
`ACCOUNTNUMBER` INT(255)
);

DROP TABLE IF EXISTS `CHECKINGACCOUNTS`;
CREATE TABLE `CHECKINGACCOUNTS`(
`NATIONALID` varchar(255),
`ACCOUNTNUMBER` int(255),
`RAMZEAVVAL` int(255),
`RAMZEDOVOM` int(255),
`REGISTERDATE` DATE,
`STATUS` ENUM('OPEN','CLOSE','SUSPENDED'),
`ACCOUNTBALANCE` fixed
);

DROP TABLE IF exists `SAVINGACCOUNTS`;
CREATE TABLE `SAVINGACCOUNTS`(
`NATIONALID` varchar(255),
`ACCOUNTNUMBER` int(255),
`RAMZEAVVAL` int(255),
`RAMZEDOVOM` int(255),
`REGISTERDATE` DATE,
`STATUS` ENUM('OPEN','CLOSE','SUSPENDED'),
`ACCOUNTBALANCE` fixed,
`INTERESTRATE` int,
`MONTHLYPAYOUT` fixed,
`HOLDDURATION` INT
);

DROP TABLE IF EXISTS `TRANSACTIONS`;
CREATE TABLE `TRANSACTIONS`(
`SOURCE` bigint(255),
`DESTINATION` bigint(255),
`RECEIPTTYPE` ENUM('TRANSFER','DEPOSIT','WITHDRAW'),
`DESCRIPTION` text,
`AMOUNT` FIXED,
`ACCOUNTNUMBER` BIGINT(255),
`DATETIME` datetime,
`ACCOUNTBALANCE`  FIXED);

DROP TABLE IF EXISTS `OPERATORS`;
CREATE TABLE `OPERATORS`(
`USERNAME` varchar(255),
`PASSWORD` INT);
INSERT INTO `OPERATORS` (`USERNAME`,`PASSWORD`) VALUES ('AMIN',1234);
INSERT INTO `OPERATORS` (`USERNAME`,`PASSWORD`) VALUES ('MEHDI',4567);
INSERT INTO `OPERATORS` (`USERNAME`,`PASSWORD`) VALUES ('MAMAD',8910);



 


